import os, subprocess

VERSION = "2.0"

# ===========================================================
#                       Network Config
# ===========================================================
HOST = '127.0.0.1'
PORT = 9999

# ===========================================================
#                       Directories Config
# ===========================================================

# Base Directories
CORE_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(CORE_DIR)
PROJECT_ROOT = os.path.dirname(SRC_DIR)

# Ensure to place the project folder inside the BizHawk directory for correct relative paths
BIZHAWK_FOLDER_DIR = os.path.dirname(PROJECT_ROOT) 

ROMS_DIR = os.path.join(PROJECT_ROOT, "roms")
STATES_DIR = os.path.join(PROJECT_ROOT, "states")
LUA_DIR = os.path.join(PROJECT_ROOT, "lua")

# Executables & Files
BIZHAWK_PATH = os.path.join(BIZHAWK_FOLDER_DIR, "EmuHawk.exe")

if not os.path.exists(BIZHAWK_PATH): raise FileNotFoundError(f"ERROR: BizHawk executable not found at {BIZHAWK_PATH}. Please check the path and try again.")

ROM_PATH = os.path.join(ROMS_DIR, "Street Fighter II' - Special Champion Edition (USA).md")
TRAINING_ENV_CLIENT_LUA_PATH = os.path.join(LUA_DIR, str("v" + VERSION), "training_env_client.lua")
MATCH_TEST_ENV_CLIENT_LUA_PATH = os.path.join(LUA_DIR, str("v" + VERSION), "match_test_env_client.lua")
INPUT_DISPLAY_LUA_PATH = os.path.join(LUA_DIR, "Input_Display.lua")
ENABLE_INPUT_DISPLAY = True
ACTIVATE_VISUALIZATION = True
ENABLE_THROTTLING = False
THROTTLE_SPEED = 250

# Player Labels for On-Screen Display
P1_MODEL_NAME = "None"
P2_MODEL_NAME = "None"



# Reset Config Lua Script Path (if needed in the future)
RESET_CONFIG_LUA_SCRIPT_PATH = os.path.join(LUA_DIR, "reset_config.lua")

def generate_lua_config():
    # Saving it in the LUA_DIR makes it easy for the main Lua script to find
    lua_config_path = os.path.join(LUA_DIR, str("v" + VERSION), "generated_config.lua")
    
    # We write it exactly how a Lua module is structured
    lua_content = f"""-- THIS FILE IS AUTOGENERATED BY PYTHON. DO NOT EDIT DIRECTLY.
local config = {{}}

config.STATES_DIR = "{STATES_DIR.replace(chr(92), chr(92)*2)}"
config.PROJECT_ROOT = "{PROJECT_ROOT.replace(chr(92), chr(92)*2)}"
config.HOST = "{HOST}"
config.PORT = {PORT}
config.ENABLE_INPUT_DISPLAY = {str(ENABLE_INPUT_DISPLAY).lower()}
config.ACTIVATE_VISUALIZATION = {str(ACTIVATE_VISUALIZATION).lower()}
config.ENABLE_THROTTLING = {str(ENABLE_THROTTLING).lower()}
config.THROTTLE_SPEED = {THROTTLE_SPEED}
config.P1_MODEL_NAME = "{P1_MODEL_NAME}"
config.P2_MODEL_NAME = "{P2_MODEL_NAME}"

return config
"""
    # Note: .replace(chr(92), chr(92)*2) is a trick to escape Windows backslashes (\ -> \\)
    
    with open(lua_config_path, "w") as f:
        f.write(lua_content)
        
    print(f"Generated Lua config at: {lua_config_path}")


# ===========================================================
#                       Directories Creation
# ===========================================================
LOG_DIR = os.path.join(PROJECT_ROOT, "logs")

def get_directory():
    directories = {
        "src": SRC_DIR,
        "project_root": PROJECT_ROOT,
        "roms": ROMS_DIR,
        "states": STATES_DIR,
        "lua": LUA_DIR,
        "logs": LOG_DIR,
        "production": os.path.join(PROJECT_ROOT, "models", "production"),
        "tuning": os.path.join(PROJECT_ROOT, "models", "tuning"),
        "tuning_logs": os.path.join(PROJECT_ROOT, "logs", "tuning")
    }
    for name, path in directories.items():
        if not os.path.exists(path):
            os.makedirs(path)
            print(f"Created missing directory: {name} with path {path}")
    return directories

# ===========================================================
#                   Model & Training Config
# ===========================================================

# ---- TESTING CONFIG ---- 
TESTING_ZIP_FILE_P1 = "models/production/PPO_MC_sf2_ryu_specialistV2_1_1_BEST_WINRATE.zip"
TESTING_PKL_FILE_P1 = "models/production/PPO_MC_sf2_ryu_specialistV2_1_1_vecnorm_BEST_WINRATE.pkl"

TESTING_ZIP_FILE_P2 = "models/production/PPO_MC_sf2_ryu_specialistV2_1_1_BEST_WINRATE.zip"
TESTING_PKL_FILE_P2 = "models/production/PPO_MC_sf2_ryu_specialistV2_1_1_vecnorm_BEST_WINRATE.pkl"

# Model Training Config
MODEL_NAME = "autocurrTest21" # PPO_MC_sf2_ryu_specialistV2_1_1
TRAINING_ZIP_FILE = "models/production/PPO_MC_sf2_ryu_specialistV2_1_1_EMERGENCY.zip"
TRAINING_PKL_FILE = "models/production/PPO_MC_sf2_ryu_specialistV2_1_1_vecnormalize_EMERGENCY.pkl"

# Model Arquitectural config
ACTION_DIM = 10 # Controler or Inputs from the AI -- DO NOT CHANGE
OBS_DIM = 10 # Includes relative X/Y and wall awareness instead of absolute coords

NUM_FRAMES = 4 # Frame Stacking = 4
MAX_STEPS_PER_ROUND = 1500 # Artificial round timeout limit
STARTING_TOTAL_TIMESTEPS = 1000 # For train production or train sinlge PPO
RESUME_PRODUCTION_TIMESTEPS = 6_000_000 # For resume production

SAVE_FREQ_STEPS = 1_000_000

# Number of parallel BizHawk instances for Optuna trials
N_ENVS = 10


# ===========================================================
#                   States Config
# ===========================================================   

# Available Savestates for Randomization
AVAILABLE_STATES = [
    "BALROG_GUILE_R1_HARD.State",
    "BLANKA_ZANGIEF_R1_HARD.State",
    "CHUNLI_ZANGIEF_R1_HARD.State",
    "DHALSIM_RYU_R1_HARD.State",
    "EHONDA_EHONDA_R1_HARD.State",
    "GUILE_GUILE_R1_HARD.State",
    "KEN_BLANKA_R1_HARD.State",
    "MBISON_KEN_R1_HARD.State",
    "RYU_BLANKA_R1_HARD.State",
    "RYU_CHUNLI_R1_HARD.State",
    "RYU_DHALSIM_R1_HARD.State",
    "RYU_EHONDA_R1_HARD.State",
    "RYU_GUILE_R1_HARD.State",
    "RYU_KEN_R1_HARD.State",
    "RYU_RYU_R1_HARD.State",
    "SAGAT_BLANKA_R1_HARD.State",
    "VEGA_KEN_R1_HARD.State",
    "ZANGIEF_RYU_R1_HARD.State"
]

RYU_ONLY_STATES_PHASE_0 = [
    "RYU_RYU_R1_PEACEFUL.State"
]

RYU_ONLY_STATES_PHASE_1 = [
    # Lvl 1
    "RYU_CHUNLI_R1_lvl1.State",
    "RYU_DHALSIM_R1_lvl1.State",
    "RYU_KEN_R1_lvl1.State",
    "RYU_ZANGIEF_R1_lvl1.State",
    "RYU_RYU_R1_lvl1.State",
    "RYU_EHONDA_R1_lvl1.State",
    "RYU_GUILE_R1_lvl1.State",
    "RYU_BALROG_R1_lvl1.State",
    "RYU_VEGA_R1_lvl1.State",
    "RYU_SAGAT_R1_lvl1.State",
    "RYU_MBISON_R1_lvl1.State",
    "RYU_BLANKA_R1_lvl1.State",
    # Lvl 2
    "RYU_BLANKA_R1_lvl2.State",
    "RYU_KEN_R1_lvl2.State",
    "RYU_EHONDA_R1_lvl2.State",
    "RYU_GUILE_R1_lvl2.State",
    "RYU_CHUNLI_R1_lvl2.State",
    "RYU_ZANGIEF_R1_lvl2.State",
    "RYU_DHALSIM_R1_lvl2.State",
    "RYU_RYU_R1_lvl2.State",
    "RYU_BALROG_R1_lvl2.State",
    "RYU_VEGA_R1_lvl2.State",
    "RYU_SAGAT_R1_lvl2.State",
    "RYU_MBISON_R1_lvl2.State",
    # Lvl 3
    "RYU_BLANKA_R1_lvl3.State",
    "RYU_DHALSIM_R1_lvl3.State",
    "RYU_RYU_R1_lvl3.State",
    "RYU_ZANGIEF_R1_lvl3.State",
    "RYU_EHONDA_R1_lvl3.State",
    "RYU_GUILE_R1_lvl3.State",
    "RYU_CHUNLI_R1_lvl3.State",
    "RYU_BALROG_R1_lvl3.State",
    "RYU_VEGA_R1_lvl3.State",
    "RYU_SAGAT_R1_lvl3.State",
    "RYU_MBISON_R1_lvl3.State",
    "RYU_KEN_R1_lvl3.State"
]

RYU_ONLY_STATES_PHASE_2 = [
    # Lvl 4
    "RYU_DHALSIM_R1_lvl4.State",
    "RYU_BLANKA_R1_lvl4.State",
    "RYU_GUILE_R1_lvl4.State",
    "RYU_CHUNLI_R1_lvl4.State",
    "RYU_RYU_R1_lvl4.State",
    "RYU_EHONDA_R1_lvl4.State",
    "RYU_BALROG_R1_lvl4.State",
    "RYU_VEGA_R1_lvl4.State",
    "RYU_SAGAT_R1_lvl4.State",
    "RYU_MBISON_R1_lvl4.State",
    "RYU_KEN_R1_lvl4.State",
    "RYU_ZANGIEF_R1_lvl4.State",
    # Lvl 5
    "RYU_RYU_R1_lvl5.State",
    "RYU_BLANKA_R1_lvl5.State",
    "RYU_CHUNLI_R1_lvl5.State",
    "RYU_KEN_R1_lvl5.State",
    "RYU_ZANGIEF_R1_lvl5.State",
    "RYU_DHALSIM_R1_lvl5.State",
    "RYU_EHONDA_R1_lvl5.State",
    "RYU_GUILE_R1_lvl5.State",
    "RYU_BALROG_R1_lvl5.State",
    "RYU_VEGA_R1_lvl5.State",
    "RYU_SAGAT_R1_lvl5.State",
    "RYU_MBISON_R1_lvl5.State"  
]

RYU_ONLY_STATES_PHASE_3 = [
    # Lvl 6
    "RYU_EHONDA_R1_lvl6.State",
    "RYU_GUILE_R1_lvl6.State",
    "RYU_CHUNLI_R1_lvl6.State",
    "RYU_RYU_R1_lvl6.State",
    "RYU_ZANGIEF_R1_lvl6.State",
    "RYU_KEN_R1_lvl6.State",
    "RYU_DHALSIM_R1_lvl6.State",
    "RYU_BLANKA_R1_lvl6.State",
    "RYU_BALROG_R1_lvl6.State",
    "RYU_VEGA_R1_lvl6.State",
    "RYU_SAGAT_R1_lvl6.State",
    "RYU_MBISON_R1_lvl6.State",
    # Lvl 7
    "RYU_DHALSIM_R1_lvl7.State",
    "RYU_KEN_R1_lvl7.State",
    "RYU_RYU_R1_lvl7.State",
    "RYU_BALROG_R1_lvl7.State",
    "RYU_BLANKA_R1_lvl7.State",
    "RYU_GUILE_R1_lvl7.State",
    "RYU_CHUNLI_R1_lvl7.State",
    "RYU_ZANGIEF_R1_lvl7.State",
    "RYU_EHONDA_R1_lvl7.State",
    "RYU_VEGA_R1_lvl7.State",
    "RYU_SAGAT_R1_lvl7.State",
    "RYU_MBISON_R1_lvl7.State"
]

RYU_ONLY_STATES_PHASE_4 = [
    # Lvl 8 Hardest
    "RYU_BALROG_R1_HARD.State",
    "RYU_BLANKA_R1_HARD.State",
    "RYU_CHUNLI_R1_HARD.State",
    "RYU_DHALSIM_R1_HARD.State",
    "RYU_EHONDA_R1_HARD.State",
    "RYU_GUILE_R1_HARD.State",
    "RYU_KEN_R1_HARD.State",
    "RYU_RYU_R1_HARD.State",
    "RYU_ZANGIEF_R1_HARD.State",
    "RYU_SAGAT_R1_HARD.State",
    "RYU_VEGA_R1_HARD.State",
    "RYU_MBISON_R1_HARD.State"
]

RYU_ONLY_STATES = (
    RYU_ONLY_STATES_PHASE_1 +
    RYU_ONLY_STATES_PHASE_2 +
    RYU_ONLY_STATES_PHASE_3 +
    RYU_ONLY_STATES_PHASE_4
)

# Reorganized difficulty levels for automated curriculum learning (8 levels, 12 states each)
LEVEL_1_STATES = [
    "RYU_CHUNLI_R1_lvl1.State",
    "RYU_DHALSIM_R1_lvl1.State",
    "RYU_KEN_R1_lvl1.State",
    "RYU_ZANGIEF_R1_lvl1.State",
    "RYU_RYU_R1_lvl1.State",
    "RYU_EHONDA_R1_lvl1.State",
    "RYU_GUILE_R1_lvl1.State",
    "RYU_BALROG_R1_lvl1.State",
    "RYU_VEGA_R1_lvl1.State",
    "RYU_SAGAT_R1_lvl1.State",
    "RYU_MBISON_R1_lvl1.State",
    "RYU_BLANKA_R1_lvl1.State",
]

LEVEL_2_STATES = [
    "RYU_BLANKA_R1_lvl2.State",
    "RYU_KEN_R1_lvl2.State",
    "RYU_EHONDA_R1_lvl2.State",
    "RYU_GUILE_R1_lvl2.State",
    "RYU_CHUNLI_R1_lvl2.State",
    "RYU_ZANGIEF_R1_lvl2.State",
    "RYU_DHALSIM_R1_lvl2.State",
    "RYU_RYU_R1_lvl2.State",
    "RYU_BALROG_R1_lvl2.State",
    "RYU_VEGA_R1_lvl2.State",
    "RYU_SAGAT_R1_lvl2.State",
    "RYU_MBISON_R1_lvl2.State",
]

LEVEL_3_STATES = [
    "RYU_BLANKA_R1_lvl3.State",
    "RYU_DHALSIM_R1_lvl3.State",
    "RYU_RYU_R1_lvl3.State",
    "RYU_ZANGIEF_R1_lvl3.State",
    "RYU_EHONDA_R1_lvl3.State",
    "RYU_GUILE_R1_lvl3.State",
    "RYU_CHUNLI_R1_lvl3.State",
    "RYU_BALROG_R1_lvl3.State",
    "RYU_VEGA_R1_lvl3.State",
    "RYU_SAGAT_R1_lvl3.State",
    "RYU_MBISON_R1_lvl3.State",
    "RYU_KEN_R1_lvl3.State",
]

LEVEL_4_STATES = [
    "RYU_DHALSIM_R1_lvl4.State",
    "RYU_BLANKA_R1_lvl4.State",
    "RYU_GUILE_R1_lvl4.State",
    "RYU_CHUNLI_R1_lvl4.State",
    "RYU_RYU_R1_lvl4.State",
    "RYU_EHONDA_R1_lvl4.State",
    "RYU_BALROG_R1_lvl4.State",
    "RYU_VEGA_R1_lvl4.State",
    "RYU_SAGAT_R1_lvl4.State",
    "RYU_MBISON_R1_lvl4.State",
    "RYU_KEN_R1_lvl4.State",
    "RYU_ZANGIEF_R1_lvl4.State",
]

LEVEL_5_STATES = [
    "RYU_RYU_R1_lvl5.State",
    "RYU_BLANKA_R1_lvl5.State",
    "RYU_CHUNLI_R1_lvl5.State",
    "RYU_KEN_R1_lvl5.State",
    "RYU_ZANGIEF_R1_lvl5.State",
    "RYU_DHALSIM_R1_lvl5.State",
    "RYU_EHONDA_R1_lvl5.State",
    "RYU_GUILE_R1_lvl5.State",
    "RYU_BALROG_R1_lvl5.State",
    "RYU_VEGA_R1_lvl5.State",
    "RYU_SAGAT_R1_lvl5.State",
    "RYU_MBISON_R1_lvl5.State",
]

LEVEL_6_STATES = [
    "RYU_EHONDA_R1_lvl6.State",
    "RYU_GUILE_R1_lvl6.State",
    "RYU_CHUNLI_R1_lvl6.State",
    "RYU_RYU_R1_lvl6.State",
    "RYU_ZANGIEF_R1_lvl6.State",
    "RYU_KEN_R1_lvl6.State",
    "RYU_DHALSIM_R1_lvl6.State",
    "RYU_BLANKA_R1_lvl6.State",
    "RYU_BALROG_R1_lvl6.State",
    "RYU_VEGA_R1_lvl6.State",
    "RYU_SAGAT_R1_lvl6.State",
    "RYU_MBISON_R1_lvl6.State",
]

LEVEL_7_STATES = [
    "RYU_DHALSIM_R1_lvl7.State",
    "RYU_KEN_R1_lvl7.State",
    "RYU_RYU_R1_lvl7.State",
    "RYU_BALROG_R1_lvl7.State",
    "RYU_BLANKA_R1_lvl7.State",
    "RYU_GUILE_R1_lvl7.State",
    "RYU_CHUNLI_R1_lvl7.State",
    "RYU_ZANGIEF_R1_lvl7.State",
    "RYU_EHONDA_R1_lvl7.State",
    "RYU_VEGA_R1_lvl7.State",
    "RYU_SAGAT_R1_lvl7.State",
    "RYU_MBISON_R1_lvl7.State",
]

LEVEL_8_STATES = [
    "RYU_BALROG_R1_HARD.State",
    "RYU_BLANKA_R1_HARD.State",
    "RYU_CHUNLI_R1_HARD.State",
    "RYU_DHALSIM_R1_HARD.State",
    "RYU_EHONDA_R1_HARD.State",
    "RYU_GUILE_R1_HARD.State",
    "RYU_KEN_R1_HARD.State",
    "RYU_RYU_R1_HARD.State",
    "RYU_ZANGIEF_R1_HARD.State",
    "RYU_SAGAT_R1_HARD.State",
    "RYU_VEGA_R1_HARD.State",
    "RYU_MBISON_R1_HARD.State",
]

DIFFICULTY_LEVELS = {
    1: LEVEL_1_STATES,
    2: LEVEL_2_STATES,
    3: LEVEL_3_STATES,
    4: LEVEL_4_STATES,
    5: LEVEL_5_STATES,
    6: LEVEL_6_STATES,
    7: LEVEL_7_STATES,
    8: LEVEL_8_STATES,
}

RYU_PVP_STATES = [
    "RYU_RYU_R1_PvP.State",
    "RYU_KEN_R1_PvP.State",
    "RYU_CHUNLI_R1_PvP.State",
    "RYU_GUILE_R1_PvP.State",
    "RYU_EHONDA_R1_PvP.State",
    "RYU_BLANKA_R1_PvP.State",
    "RYU_ZANGIEF_R1_PvP.State",
    "RYU_DHALSIM_R1_PvP.State",
    "RYU_BALROG_R1_PvP.State",
    "RYU_VEGA_R1_PvP.State",
    "RYU_SAGAT_R1_PvP.State",
    "RYU_MBISON_R1_PvP.State"
]



CURRICULUM_PHASES = [
    RYU_ONLY_STATES_PHASE_1,   # Now Phase 0 — easy but live opponents, diverse states
    RYU_ONLY_STATES_PHASE_2,   # Phase 1
    RYU_ONLY_STATES_PHASE_3,   # Phase 2
    RYU_ONLY_STATES_PHASE_4,   # Phase 3 — full difficulty
]

TRAINING_STATES = CURRICULUM_PHASES[0] # Global variable to be updated by the callback and read by the env

# Curriculum advancement gate
WIN_RATE_THRESHOLD = 0.75
WIN_RATE_WINDOW = 250

CUSTOM_STATES = ["Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave7.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave9.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave4.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave3.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave5.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave0.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave1.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave8.State", "Street Fighter II - Special Champion Edition U .Genplus-gx.QuickSave6.State"]
