-- THIS FILE IS AUTOGENERATED BY PYTHON. DO NOT EDIT DIRECTLY.
local config = {}

config.STATES_DIR = "c:\\Users\\Diego Perea\\Documents\\Apps\\BizHawk-2.8-win-x64\\street_fighter\\states"
config.PROJECT_ROOT = "c:\\Users\\Diego Perea\\Documents\\Apps\\BizHawk-2.8-win-x64\\street_fighter"
config.HOST = "127.0.0.1"
config.PORT = 9999

return config
